### ISSUE TITLE
One of the MFE file can't extract

### ISSUE THREAD

**Issue by uniraymon** [adelosa/mciutil#30]
Dear sir, 
thanks so much for your tool as it help me so much.There is some issue when I try extract the file which generate from Mastercard at last week.

![image](https://cloud.githubusercontent.com/assets/22536650/18980869/253189b4-870b-11e6-8f36-610b492511d2.png)

I am thinking is that have any new format coming from Mastercard, as I can extract this file by using the MFE simulator after update the simulator to latest version.

There is the issue MFE folder, hope it can help you to handle this issue.

[TT112T0.zip](https://github.com/adelosa/mciutil/files/502173/TT112T0.zip)

**Comment by adelosa** [comment]
Hi there, glad to see the tool can be of use to others. Thanks for reporting the issue.
By looking at this file, I suspect that there is an error in the tool regarding the decode of the merchant name (de43). The merchant in error has the name "GOLDEN FIELD CAF__E__". The e is actually an accented e (0xc9) and this is not a valid value in ASCII which is the default encoding used. 
I will have a look and see if I can make the encoding of the utility work with UTF-8 and let you know. I will probably have to release a new version of the tool to get this working.

**Comment by adelosa** [comment]
Version 0.4.8 has been updated to handle latin1 encoding which is what was causing the issue. I have processed your sample file with this version and it successfully extracts the records including the latin characters. The files generated are encoded with UTF-8.. I may at some point add some options around this, but its the most obvious choice for most people.
Can you please install the new version using `pip install -U mciutil` and let me know how you go.

**Comment by uniraymon** [comment]
Thanks for ur fast response!!!
I will test it now


Thanks and regards,
Raymond Wong

2016-10-02 20:17 GMT+08:00 Anthony Delosa <notifications@github.com>:

**Comment by uniraymon** [comment]
It works now!!
Thanks you so much!!

Thanks and regards,
Raymond Wong

2016-10-03 12:19 GMT+08:00 Raymond Wong <unitw.raymond@gmail.com>:

**Comment by bundle94** [comment]
pls paramconv --help is not working on my machine
