### ISSUE TITLE
Creating MC IPM file Test sample file and process

### ISSUE THREAD

**Issue by Kurukshetran** [adelosa/mciutil#45]
How to create EBCDIC IPM file from csv file? Help is appreciated.

**Comment by adelosa** [comment]
I’m currently rewriting the utility at the moment. This was my first python project and I’m quite a bit better at it now.  The new version will support extraction both ways. I’ll update here when it is released.

**Comment by adelosa** [comment]
The new module is now available on pypi

    pip install cardutil

Source available at https://bitbucket.org/hoganman/cardutil.

It's python 3 only but does support creation of Mastercard IPM files.
The following code reads in a CSV file and outputs a 1014 blocked ebcdic IPM file. 

    from csv import DictReader
    from cardutil.mciipm import IpmWriter

    with open('in.csv', 'r') as csv_in, open('out.ipm', 'wb') as ipm_out:
        reader = DictReader(csv_in)
        writer = IpmWriter(ipm_out, encoding='cp500', blocked=True)
        for row in reader:
            writer.write(row)
        writer.close()

I will eventually add this as a command line utility.. for now you'll need to add this code to use.

**Comment by pellegrinimarcos** [comment]
how is the in.csv file format please

**Comment by adelosa** [comment]
Mciutil cannot create IPM files. You will need to use cardutil. Please raise questions about cardutil on that repo. See https://bitbucket.org/hoganman/cardutil. 
The tool you need is https://cardutil.readthedocs.io/en/latest/cli.html#mci-csv-to-ipm.

**Comment by charisad** [comment]
Hi, can you suggest a solution for the same question in Java?

**Comment by adelosa** [comment]
> Hi, can you suggest a solution for the same question in Java?

No - but you are free to rewrite in Java using the code here to work things out.
